# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Ian Turcotte
tagline:          'blog'
description:      'My personal blog.'
url:              http://ianturcotte.github.io
baseurl:          

author:
  name:           Ian Turcotte
  url:            https://facebook.com/ianturcotte

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
  - icon:         twitter
    url:          https://twitter.com/iturcotte
    desc:         Follow me on twitter

  - icon:         facebook
    url:          https://facebook.com/ianturcotte
    desc:         Follow me on facebook

  - icon:         github
    url:          https://github.com/ianturcotte
    desc:         Fork me on github


  - icon:         feed
    url:          http://ianturcotte.github.io/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         Ian Turcotte
  url:            http://ianturcotte.github.io
  type_title:     All rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
